### ISSUE TITLE
Docs for adding current version bin path to $PATH

### ISSUE THREAD

**Issue by imlucas** [mongodb-js/version-manager#94]
If `~/.mongodb/versions/mongodb-current/bin` is in your `$PATH`, when you run `mongo`, `mongod`, etc everything will work as expected.  If not, you end up in a terrible place.  Figure out a good way to tell the user to add `~/.mongodb/versions/mongodb-current/bin` to `$PATH` and how to warn them if it's not.

**Comment by pzrq** [comment]
I'd need to study this more to write something good, but one example I've come across that suggests `$PATH` and appears to have considered several different approaches: 

... **pyenv _does not..._**
* **Need to be loaded into your shell.** Instead, pyenv's shim approach works by adding a directory to your `$PATH`.

https://github.com/yyuu/pyenv#in-contrast-with-pythonbrew-and-pythonz-pyenv-does-not

**Comment by pzrq** [comment]
Another example
https://yarnpkg.com/en/docs/install#path-setup

**Comment by mymainmanbrown** [comment]
Environment - Linux Mint 18 (Ubuntu 16.04)

I am running node via n, rather than running node as a "globally" installed package.  I installed this project without sudo:
`npm install -g mongodb-version-manager`

I first ran into the issue of mongo not being available on the $PATH, so I took a look at https://github.com/mongodb-js/version-manager/issues/94.  After understanding where the executables lived, I tried running:
`~/.mongodb/versions/mongodb-current/bin/mongo`
Which didn't work.  I figured this was due to the port being accessible only via sudo, so I tried running it as sudo:
`sudo ~/.mongodb/versions/mongodb-current/bin/mongo`
But I still received the "connection refused" error.

After running:
`sudo mkdir -p /data/db`
I was able to get mongod working:
`sudo ~/.mongodb/versions/mongodb-current/bin/mongod`

At which point I realized that (of course) mongod has to be running before I can make a connection using mongo.  I had forgotten about this since Ubuntu installations of mongo start the service automatically and at every startup, and I know that this piece of information is specific to mongo, not this version manager, but I figured I'd document my experience here so that the "getting started" documentation can be improved (or created), and to indicate that it seems that /data/db will be shared by any version of mongo that is used by this manager.  Perhaps it doesn't end up making a difference, but it seems to me that a version manager like this should "sandbox" all mongo instances from one another.

**Comment by mymainmanbrown** [comment]
I added the following line to my `~/.bashrc` file:

`export M_PREFIX="$HOME/.mongodb/versions/mongodb-current"; [[ :$PATH: == *":$M_PREFIX/bin:"* ]] || PATH+=":$M_PREFIX/bin"`

Which was completely ripped off from the entry by n:

`export N_PREFIX="$HOME/n"; [[ :$PATH: == *":$N_PREFIX/bin:"* ]] || PATH+=":$N_PREFIX/bin"  # Added by n-install (see http://git.io/n-install-repo).`

And of course, don't forget to run:

`~/.bashrc`

to get immediate access to it.

**Comment by meowsus** [comment]
@imlucas @pzrq I've added a PR to update the usage docs.

This should allow us to get around the `sudo` problem fairly well. It outlines what directory to add to your PATH and how to create a data director within `mongodb-current` that would be specific to the current version. Since this is all done in the user's home directory, `sudo` would not be required.

I've got a mongorestore job running right now using these settings. Huzzah!

cc: @brainthinks

**Comment by pzrq** [comment]
@meowsus @brainthinks Thanks for reaching out 👍 

https://docs.mongodb.com/manual/reference/program/#mongodb-package-components

The above will hopefully help explain a few things that appear to have confused you both in the past learning about how MongoDB works (I think you both understand it all now 😄 ), and help improve the documentation in this repository, @satyasinha may also add more specific suggestions to the PR.

For example, it's not yet clear to me if [`--dbpath`](https://docs.mongodb.com/manual/reference/program/mongod/index.html#cmdoption-dbpath) is something that should be managed by or coupled to this `mongodb-version-manager` - there could just as easily be a `mongodb-dbpath-manager`, and both could be coupled into [`mongodb-runner`](https://github.com/mongodb-js/runner), except you'd then have the surprising change of now managing the `--dbpath` for existing users of `mongodb-version-manager`.
